USE imdb;

-- 2--Find the total number of rows in each table of the schema.
SELECT table_name,TABLE_ROWS
FROM   INFORMATION_SCHEMA.TABLES
WHERE  TABLE_SCHEMA = 'imdb'; 

-- 3 -- Identify which columns in the movie table have null values.
SELECT 'ID'
FROM   MOVIE
WHERE  ID IS NULL
UNION
SELECT 'Title'
FROM   MOVIE
WHERE  TITLE IS NULL
UNION
SELECT 'Year'
FROM   MOVIE
WHERE  YEAR IS NULL
UNION
SELECT 'Date Published'
FROM   MOVIE
WHERE  DATE_PUBLISHED IS NULL
UNION
SELECT 'Movie'
FROM   MOVIE
WHERE  DURATION IS NULL
UNION
SELECT 'Country'
FROM   MOVIE
WHERE  COUNTRY IS NULL
UNION
SELECT 'WorldWide_Gross'
FROM   MOVIE
WHERE  WORLWIDE_GROSS_INCOME IS NULL
UNION
SELECT 'Languages'
FROM   MOVIE
WHERE  LANGUAGES IS NULL
UNION
SELECT 'Prod Company'
FROM   MOVIE
WHERE  PRODUCTION_COMPANY IS NULL;